apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-job-api
  namespace: default
  labels:
    app: ml-job-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-job-api
  template:
    metadata:
      labels:
        app: ml-job-api
    spec:
      serviceAccountName: fastapi-sa
      containers:
      - name: api
        image: gcr.io/${PROJECT_ID}/fastapi-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: KUBERNETES_PORT
          value: "tcp://10.0.0.1:443" # Dummy env var just to trigger incluster config
        - name: PROJECT_ID
          value: "${PROJECT_ID}"
        - name: OUTPUT_BUCKET
          value: "gs://${PROJECT_ID}-boltz-outputs"
        - name: INPUT_BUCKET
          value: "gs://${PROJECT_ID}-boltz-inputs"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
