apiVersion: v1
kind: Service
metadata:
  name: ml-job-api-service
  namespace: default
  annotations:
    cloud.google.com/backend-config: '{"default": "api-iap-backendconfig"}'
spec:
  type: NodePort
  selector:
    app: ml-job-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
